name: learn golang deployment
#run-name: ${{github.actor}} is learning Github Actions

on:
  push:
    branches:
      - golang/*
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20.4'
#          check-latest: true
      - name: Check Go version
      - run: go version
