name: golang ci/cd
run-name: learning Github Actions for beego framework

env:
  PRIVATE_KEY: ${{secrets.KEY}}

on:
  push:
    branches:
      - golang/*
  pull_request:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20.4'
#          check-latest: true

      - name: Check Go version
        run: go version

      - name: Install Beego and dependencies
        run: |
          go install github.com/beego/beego/v2  
          go install github.com/beego/bee@latest

#          go get -u github.com/beego/beego/v2 // use this in different purpose read later

## we will update or install dependency through dep later
##      - name: Install dep
##        run: go get -v github.com/golang/dep/cmd/dep
##
##      - name: Install dependencies
##        run: dep ensure
#
      - name: Install dependencies
        run: |
          go mod tidy
      - name: test
        run: go test ./...

      - name: build
        run: go build -o testCiCd

      - name: copy to server
        run: |
          echo "${{env.PRIVATE_KEY}}" > private_key && chmod 600 private_key
          scp -vvv  -P 40405 -i private_key  -o StrictHostKeyChecking=no ./dist/testCiCd ubuntu@103.199.168.131:/home/system/Test/Go/testCiCd
#
#      - name: Copy built binary to server via SSH
#        uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USER }}
#          password: ${{ secrets.KEY }}
#          source: ./app
#          target: /path/to/deploy/directory/


#
##
##  # build the executable file as then name testCiCd
##  build:
##    runs-on: ubuntu-latest
##    steps:
##      - name: build
##        run: go build #-o testCiCd
##  #      - name: run
##  #        run: bee run
#
#  test:
#    runs-on: ubuntu-latest
#
#    steps:
#      #    - name: Install dependencies
#      #      run: |
#      #        go mod download github.com/smartystreets/goconvey
