name: learn golang deployment
run-name: ${{github.actor}} is learning Github Actions

on:
  push:
    branches:
      - golang/*
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

  build1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Node.js 2222
        uses: actions/setup-node@v4
        with:
          node-version: 20